# ベースイメージとしてNode.js 20を使用
FROM node:20

# 作業ディレクトリを設定
WORKDIR /app

# package.jsonとyarn.lockをコピー
COPY package.json yarn.lock ./

# 依存関係をインストール
RUN yarn install

# ソースコードをコピー
COPY . .

# 開発サーバーを起動
CMD ["yarn", "dev", "--host", "0.0.0.0"]
