# fly.toml app configuration file generated for enkansan on 2024-07-08T06:47:03+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'enkansan'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
